name: politics-mc
version: '1.0-SNAPSHOT'
main: funn.j2k.politicsMcPlugin.PoliticsMcPlugin
api-version: '1.21'
load: STARTUP
authors: [ shebik ]
description: My plugin for politics
website: j2k.fun


commands:
  maps:
    description: Open the maps menu
    permission: politics-mc-plugin.maps

permissions:
  politics-mc.maps:
    description: Allows access to the items command
    default: op
